# Generated by Django 4.2.11 on 2025-09-19 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('it', 'IT & Software'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('design', 'Design'), ('hr', 'HR & Admin'), ('sales', 'Sales'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full-time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('lead', 'Lead/Manager (10+ years)')], default='entry', max_length=20)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], default='office', max_length=20)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_display', models.CharField(help_text='e.g., ₹8-15 LPA', max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list, help_text='List of required skills')),
                ('company_logo', models.CharField(default='🏢', help_text='Emoji for company logo', max_length=10)),
                ('company_size', models.CharField(choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('medium', 'Medium (201-1000)'), ('large', 'Large (1000+)')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
