import os
import sys
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from jobs.models import Job

jobs_data = [
    {
        "title": "Frontend Developer",
        "company": "TCS",
        "location": "Mumbai, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "hybrid",
        "min_salary": 400000,
        "max_salary": 700000,
        "salary_display": "₹4-7 LPA",
        "description": "We are looking for a skilled Frontend Developer to join our team. You will be responsible for building user-friendly web applications using React.js and modern JavaScript.",
        "requirements": "Bachelor's degree in Computer Science or related field. Strong knowledge of HTML, CSS, JavaScript. Experience with React.js or Angular.",
        "skills": ["React.js", "JavaScript", "HTML", "CSS", "Git"],
        "company_logo": "🏢",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Python Developer",
        "company": "Infosys",
        "location": "Bangalore, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "office",
        "min_salary": 800000,
        "max_salary": 1200000,
        "salary_display": "₹8-12 LPA",
        "description": "Join our Python development team to build scalable backend systems. Work with Django, FastAPI, and cloud technologies.",
        "requirements": "3+ years experience in Python. Knowledge of Django/Flask. Experience with REST APIs and databases.",
        "skills": ["Python", "Django", "REST API", "PostgreSQL", "AWS"],
        "company_logo": "💻",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Data Analyst",
        "company": "Wipro",
        "location": "Pune, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "hybrid",
        "min_salary": 500000,
        "max_salary": 800000,
        "salary_display": "₹5-8 LPA",
        "description": "Analyze large datasets to provide business insights. Create dashboards and reports using Power BI and Python.",
        "requirements": "Strong analytical skills. Knowledge of SQL, Python, Excel. Experience with data visualization tools.",
        "skills": ["Python", "SQL", "Power BI", "Excel", "Statistics"],
        "company_logo": "📊",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Digital Marketing Executive",
        "company": "Zomato",
        "location": "Gurugram, India",
        "category": "marketing",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "office",
        "min_salary": 300000,
        "max_salary": 500000,
        "salary_display": "₹3-5 LPA",
        "description": "Drive digital marketing campaigns across social media, Google Ads, and email marketing. Analyze campaign performance.",
        "requirements": "Knowledge of SEO, SEM, Social Media Marketing. Experience with Google Analytics and Facebook Ads.",
        "skills": ["SEO", "Google Ads", "Social Media", "Analytics", "Content Marketing"],
        "company_logo": "🍕",
        "company_size": "medium",
        "is_active": True
    },
    {
        "title": "Backend Developer Intern",
        "company": "SkillConnect Labs",
        "location": "Remote",
        "category": "it",
        "job_type": "internship",
        "experience_level": "entry",
        "work_mode": "remote",
        "min_salary": 10000,
        "max_salary": 20000,
        "salary_display": "₹10-20K/month",
        "description": "Learn and work on real projects. Build APIs using Django and Node.js. Great learning opportunity for freshers.",
        "requirements": "Currently pursuing or recently completed degree in CS/IT. Basic knowledge of Python or JavaScript.",
        "skills": ["Python", "Django", "Node.js", "Git", "REST API"],
        "company_logo": "🚀",
        "company_size": "startup",
        "is_active": True
    },
    {
        "title": "UI/UX Designer",
        "company": "Flipkart",
        "location": "Bangalore, India",
        "category": "design",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "hybrid",
        "min_salary": 1000000,
        "max_salary": 1500000,
        "salary_display": "₹10-15 LPA",
        "description": "Design beautiful and intuitive user interfaces for our e-commerce platform. Conduct user research and usability testing.",
        "requirements": "3+ years of UI/UX experience. Proficiency in Figma, Adobe XD. Strong portfolio required.",
        "skills": ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Systems"],
        "company_logo": "🛒",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "HR Executive",
        "company": "Reliance Industries",
        "location": "Mumbai, India",
        "category": "hr",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "office",
        "min_salary": 350000,
        "max_salary": 500000,
        "salary_display": "₹3.5-5 LPA",
        "description": "Handle recruitment, employee onboarding, and HR operations. Manage employee records and payroll processing.",
        "requirements": "MBA in HR or related field. Good communication skills. Knowledge of HR software.",
        "skills": ["Recruitment", "Employee Relations", "Payroll", "MS Office", "Communication"],
        "company_logo": "🏭",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Full Stack Developer",
        "company": "Amazon",
        "location": "Hyderabad, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "senior",
        "work_mode": "hybrid",
        "min_salary": 2500000,
        "max_salary": 4000000,
        "salary_display": "₹25-40 LPA",
        "description": "Build and maintain large-scale distributed systems. Work with React, Node.js, and AWS services.",
        "requirements": "6+ years of full stack development experience. Strong problem-solving skills. Experience with microservices.",
        "skills": ["React", "Node.js", "AWS", "MongoDB", "Microservices"],
        "company_logo": "📦",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Content Writer",
        "company": "Times of India",
        "location": "Delhi, India",
        "category": "marketing",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "office",
        "min_salary": 200000,
        "max_salary": 400000,
        "salary_display": "₹2-4 LPA",
        "description": "Write engaging articles, blogs, and news content. Research trending topics and create SEO-optimized content.",
        "requirements": "Excellent writing skills in English/Hindi. Knowledge of SEO. Journalism or Mass Communication degree preferred.",
        "skills": ["Content Writing", "SEO", "Research", "Editing", "Social Media"],
        "company_logo": "📰",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Sales Executive",
        "company": "HDFC Bank",
        "location": "Solapur, India",
        "category": "sales",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "office",
        "min_salary": 250000,
        "max_salary": 400000,
        "salary_display": "₹2.5-4 LPA",
        "description": "Sell banking products like loans, credit cards, and insurance. Meet monthly sales targets and build customer relationships.",
        "requirements": "Graduate in any discipline. Good communication skills. Willingness to do field work.",
        "skills": ["Sales", "Communication", "Negotiation", "Customer Service", "Banking"],
        "company_logo": "🏦",
        "company_size": "large",
        "is_active": True
    },
    # New Jobs Added
    {
        "title": "React Native Developer",
        "company": "Paytm",
        "location": "Noida, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "hybrid",
        "min_salary": 1200000,
        "max_salary": 2000000,
        "salary_display": "₹12-20 LPA",
        "description": "Build cross-platform mobile apps for India's leading fintech platform. Work on payment features used by millions.",
        "requirements": "3+ years React Native. Experience with Redux, TypeScript. Knowledge of iOS/Android deployment.",
        "skills": ["React Native", "TypeScript", "Redux", "JavaScript", "REST API"],
        "company_logo": "💳",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Google",
        "location": "Bangalore, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "senior",
        "work_mode": "hybrid",
        "min_salary": 3500000,
        "max_salary": 6000000,
        "salary_display": "₹35-60 LPA",
        "description": "Design and implement ML models for Google products. Work on cutting-edge AI research and deployment.",
        "requirements": "5+ years ML experience. PhD preferred. Strong Python, TensorFlow/PyTorch. Publications in top conferences.",
        "skills": ["Python", "TensorFlow", "PyTorch", "Machine Learning", "Deep Learning", "NLP"],
        "company_logo": "🔍",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "DevOps Engineer",
        "company": "Razorpay",
        "location": "Bangalore, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "office",
        "min_salary": 1500000,
        "max_salary": 2500000,
        "salary_display": "₹15-25 LPA",
        "description": "Manage cloud infrastructure for payment processing. Ensure 99.99% uptime for critical financial systems.",
        "requirements": "3+ years DevOps. AWS/GCP expertise. Kubernetes, Docker, Terraform. CI/CD experience.",
        "skills": ["AWS", "Kubernetes", "Docker", "Terraform", "Jenkins", "Linux"],
        "company_logo": "💰",
        "company_size": "medium",
        "is_active": True
    },
    {
        "title": "Product Manager",
        "company": "Swiggy",
        "location": "Bangalore, India",
        "category": "other",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "hybrid",
        "min_salary": 2000000,
        "max_salary": 3500000,
        "salary_display": "₹20-35 LPA",
        "description": "Lead product strategy for food delivery features. Drive growth through data-driven product decisions.",
        "requirements": "4+ years product management. Experience with consumer apps. Strong analytical skills. MBA preferred.",
        "skills": ["Product Strategy", "Data Analysis", "Agile", "User Research", "Roadmapping"],
        "company_logo": "🍔",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Graphic Designer",
        "company": "Nykaa",
        "location": "Mumbai, India",
        "category": "design",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "office",
        "min_salary": 400000,
        "max_salary": 700000,
        "salary_display": "₹4-7 LPA",
        "description": "Create stunning visuals for India's top beauty e-commerce platform. Design for web, social, and print.",
        "requirements": "1+ years design experience. Proficiency in Adobe Creative Suite. Strong portfolio required.",
        "skills": ["Photoshop", "Illustrator", "Figma", "Canva", "Brand Design"],
        "company_logo": "💄",
        "company_size": "medium",
        "is_active": True
    },
    {
        "title": "Cybersecurity Analyst",
        "company": "ICICI Bank",
        "location": "Mumbai, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "office",
        "min_salary": 1000000,
        "max_salary": 1800000,
        "salary_display": "₹10-18 LPA",
        "description": "Protect critical banking infrastructure. Monitor threats, conduct security audits, and implement security measures.",
        "requirements": "3+ years cybersecurity. CISSP/CEH certification. Experience with SIEM, firewalls, penetration testing.",
        "skills": ["Cybersecurity", "SIEM", "Penetration Testing", "Network Security", "Incident Response"],
        "company_logo": "🔐",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Business Analyst",
        "company": "Accenture",
        "location": "Pune, India",
        "category": "finance",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "hybrid",
        "min_salary": 600000,
        "max_salary": 1000000,
        "salary_display": "₹6-10 LPA",
        "description": "Analyze business processes and create solutions for Fortune 500 clients. Bridge gap between business and tech.",
        "requirements": "0-2 years experience. Strong analytical skills. Excel, SQL knowledge. MBA fresher welcome.",
        "skills": ["Business Analysis", "SQL", "Excel", "Requirements Gathering", "Documentation"],
        "company_logo": "📈",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Android Developer",
        "company": "PhonePe",
        "location": "Bangalore, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "hybrid",
        "min_salary": 1400000,
        "max_salary": 2200000,
        "salary_display": "₹14-22 LPA",
        "description": "Build features for India's #1 payments app with 500M+ users. Work on performance optimization and new features.",
        "requirements": "3+ years Android. Kotlin, Jetpack Compose. Experience with large-scale apps. Performance optimization.",
        "skills": ["Kotlin", "Android", "Jetpack Compose", "MVVM", "Room Database"],
        "company_logo": "📱",
        "company_size": "large",
        "is_active": True
    },
    {
        "title": "Social Media Manager",
        "company": "Mamaearth",
        "location": "Gurugram, India",
        "category": "marketing",
        "job_type": "full-time",
        "experience_level": "entry",
        "work_mode": "office",
        "min_salary": 350000,
        "max_salary": 600000,
        "salary_display": "₹3.5-6 LPA",
        "description": "Manage social media presence for D2C beauty brand. Create engaging content and grow online community.",
        "requirements": "1+ years social media experience. Creative content skills. Knowledge of Instagram, YouTube, Facebook ads.",
        "skills": ["Social Media", "Content Creation", "Instagram", "Influencer Marketing", "Analytics"],
        "company_logo": "🌿",
        "company_size": "medium",
        "is_active": True
    },
    {
        "title": "QA Engineer",
        "company": "Freshworks",
        "location": "Chennai, India",
        "category": "it",
        "job_type": "full-time",
        "experience_level": "mid",
        "work_mode": "remote",
        "min_salary": 900000,
        "max_salary": 1500000,
        "salary_display": "₹9-15 LPA",
        "description": "Ensure quality for SaaS products used by 60,000+ businesses worldwide. Build automated testing frameworks.",
        "requirements": "2+ years QA experience. Selenium, Cypress automation. API testing. Agile methodology.",
        "skills": ["Selenium", "Cypress", "API Testing", "Test Automation", "JIRA"],
        "company_logo": "✅",
        "company_size": "large",
        "is_active": True
    },
]

print("Adding jobs to database...")
count = 0
for job_data in jobs_data:
    job, created = Job.objects.get_or_create(
        title=job_data["title"],
        company=job_data["company"],
        defaults=job_data
    )
    if created:
        count += 1
        print(f"✅ Added: {job.title} at {job.company}")
    else:
        print(f"⏭️ Already exists: {job.title} at {job.company}")

print(f"\n🎉 Done! {count} new jobs added. Total jobs: {Job.objects.count()}")
