# DigitalOcean App Platform Configuration
# Deploy: doctl apps create --spec app.yaml

name: skillconnect-backend
region: nyc

# PostgreSQL Database
databases:
  - name: skillconnect-db
    engine: PG
    version: "15"
    production: false
    cluster_name: skillconnect-cluster

# Web Service
services:
  - name: web
    # GitHub Integration
    github:
      repo: nijamuddinmujawar77-coder/skillconnect-backend
      branch: main
      deploy_on_push: true
    
    # Build Configuration
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    
    # Run Configuration
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2 --threads 2
    
    # Instance Configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP Configuration
    http_port: 8000
    
    routes:
      - path: /
    
    # Health Check
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment Variables
    envs:
      - key: DEBUG
        value: "False"
      
      - key: PYTHON_VERSION
        value: "3.12.0"
      
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "your-secret-key-here-generate-strong-one"
      
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "your-groq-api-key"
      
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "${skillconnect-db.DATABASE_URL}"
      
      - key: ALLOWED_HOSTS
        value: ".ondigitalocean.app,.digitalocean.app,skillconnect.dev,www.skillconnect.dev,api.skillconnect.dev"
      
      - key: DJANGO_SETTINGS_MODULE
        value: "core.settings"
      
      - key: CORS_ALLOWED_ORIGINS
        value: "https://skillconnect.dev,https://www.skillconnect.dev"

# Pre-Deploy Jobs (Migrations)
jobs:
  - name: migrate
    kind: PRE_DEPLOY
    
    run_command: |
      python manage.py migrate --no-input
      python create_admin.py || true
      python add_jobs.py || true
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: "${skillconnect-db.DATABASE_URL}"
