# Generated by Django 4.2.7 on 2025-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_bookmarked_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interview_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_applications',
            field=models.IntegerField(default=0),
        ),
    ]
